sudo: false
language: c

install:
  # check install script works
  - bash <(curl -sSL https://github.com/robbinch/travis-nix-proot/raw/master/install)
  # overwrite installed script
  - install travis-nix-proot $HOME/.travis-nix-proot/bin/
  - export PATH=$HOME/.travis-nix-proot/bin:$PATH
  - travis-nix-proot setup

script:
  - travis-nix-proot nix-env -i bats
  - travis-nix-proot bats test.sh

before_cache:
  - travis-nix-proot gc
  - travis-nix-proot dump-db

cache:
  directories:
    - $HOME/travis-nix-proot.cache
