#!/bin/sh

set -o errexit

dst=$HOME/.travis-nix-proot/bin
mkdir -p "$dst"
curl -OL https://github.com/robbinch/travis-nix-proot/raw/master/travis-nix-proot && install travis-nix-proot "$dst"

echo "Installed travis-nix-proot to $dst."